version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: claimback
      POSTGRES_PASSWORD: claimback_dev
      POSTGRES_DB: claimback
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
