[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_RUNTIME = "nodejs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mammoth", "pdfmake", "@prisma/client"]
  included_files = ["prisma/schema.prisma", "node_modules/.prisma/**"]
