import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = { title: 'Terms of Service — SignGuard' }

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12 space-y-8">
      <div>
        <Link href="/" className="text-sm text-primary hover:underline">&larr; Back to home</Link>
        <h1 className="text-3xl font-bold mt-4">Terms of Service</h1>
        <p className="text-muted-foreground mt-1">Last updated: March 2026</p>
      </div>

      <section className="space-y-4 text-sm leading-relaxed">
        <h2 className="text-xl font-semibold">1. Service Description</h2>
        <p>SignGuard provides AI-powered contract analysis to help users understand the terms, risks, and implications of commercial agreements. The service uses Anthropic&apos;s Claude AI to analyze uploaded documents and generate structured risk reports.</p>

        <h2 className="text-xl font-semibold text-red-600 dark:text-red-400">2. Not Legal Advice — Important</h2>
        <p><strong>SignGuard is not a law firm and does not provide legal advice.</strong> Our analysis is generated by artificial intelligence and is provided for informational purposes only. AI analysis may contain errors, omissions, or misinterpretations of contract terms.</p>
        <p>You should not rely solely on SignGuard&apos;s analysis for legal, financial, or business decisions. For contracts involving significant commitments, employment terms, or legal rights, we strongly recommend consulting a qualified attorney in the relevant jurisdiction.</p>

        <h2 className="text-xl font-semibold">3. Limitation of Liability</h2>
        <p>SignGuard is provided &quot;as is&quot; without warranties of any kind, express or implied. We do not guarantee the completeness, accuracy, or reliability of any analysis.</p>
        <p>To the maximum extent permitted by law, SignGuard and its operators shall not be liable for any direct, indirect, incidental, consequential, or special damages arising from your use of the service or any decisions made based on our analysis.</p>

        <h2 className="text-xl font-semibold">4. User Responsibilities</h2>
        <ul className="list-disc list-inside space-y-1">
          <li>You warrant that you have the right to upload any document you submit for analysis</li>
          <li>You must not upload documents containing sensitive personal data of third parties without authorization</li>
          <li>You must not use the service for illegal purposes</li>
          <li>You are responsible for verifying any findings independently before acting on them</li>
        </ul>

        <h2 className="text-xl font-semibold">5. Document Handling</h2>
        <p>Documents are processed in memory and never stored on our servers. Text is extracted client-side, sent to our AI provider for analysis, and discarded. Only the AI-generated analysis results are stored in your account.</p>

        <h2 className="text-xl font-semibold">6. Pricing and Payment</h2>
        <p>SignGuard offers free scans during the beta period. Pricing is subject to change with reasonable notice. Current pricing is displayed on our <Link href="/#pricing" className="text-primary hover:underline">pricing page</Link>.</p>

        <h2 className="text-xl font-semibold">7. Account Termination</h2>
        <p>You may delete your account at any time. We reserve the right to suspend or terminate accounts that violate these terms. Upon termination, your scan results will be permanently deleted.</p>

        <h2 className="text-xl font-semibold">8. Intellectual Property</h2>
        <p>The SignGuard service, brand, and analysis methodology are our intellectual property. Your documents remain your property. The AI-generated analysis reports are provided for your personal or business use.</p>

        <h2 className="text-xl font-semibold">9. Governing Law</h2>
        <p>These terms are governed by the laws of the Federal Republic of Germany. For consumers in the EU, mandatory consumer protection laws of your country of residence apply in addition.</p>

        <h2 className="text-xl font-semibold">10. Changes to Terms</h2>
        <p>We may update these terms. Material changes will be communicated via the app or email. Continued use after changes constitutes acceptance.</p>

        <h2 className="text-xl font-semibold">11. Severability</h2>
        <p>If any provision of these terms is found unenforceable, the remaining provisions continue in full force and effect.</p>
      </section>
    </div>
  )
}
