import { ParsedEmail } from '@/lib/gmail/parser'

export const demoEmails: ParsedEmail[] = [
  {
    messageId: 'demo-001',
    subject: 'Your monthly subscription renewal - Premium Plan',
    from: 'billing@streamflix.com',
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    bodyText: 'Your StreamFlix Premium subscription has been renewed for $15.99/month. This is an automatic charge to your Visa ending in 4242. You have been subscribed since January 2024. To manage your subscription, visit your account settings.',
  },
  {
    messageId: 'demo-002',
    subject: 'Payment receipt for CloudStorage Plus',
    from: 'noreply@cloudstorage.io',
    date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    bodyText: 'Thank you for your payment of $9.99 for CloudStorage Plus (2TB plan). Your next billing date is April 15, 2026. You are currently using 45GB of 2TB storage.',
  },
  {
    messageId: 'demo-003',
    subject: 'Invoice #INV-2026-0392 - FitTracker Pro',
    from: 'billing@fittracker.app',
    date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    bodyText: 'Your annual FitTracker Pro subscription has been charged: $79.99/year. Your last login was 8 months ago. Consider if you still need this subscription.',
  },
  {
    messageId: 'demo-004',
    subject: 'Your electricity bill is higher than usual',
    from: 'alerts@powerco.com',
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    bodyText: 'Your electricity bill for March 2026 is $287.50, which is 40% higher than your average of $205. This may be due to seasonal changes or an error in meter reading. If you believe this is incorrect, please contact us.',
  },
  {
    messageId: 'demo-005',
    subject: 'Price drop alert: Laptop you purchased',
    from: 'deals@techmart.com',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    bodyText: 'Good news! The TechPro Laptop X15 you purchased on February 20 for $1,299.99 is now available for $1,099.99 — a savings of $200! Many retailers offer price adjustment within 30 days of purchase.',
  },
  {
    messageId: 'demo-006',
    subject: 'Your flight has been delayed — Booking #FLY892',
    from: 'notifications@skyairlines.com',
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    bodyText: 'We regret to inform you that your flight SA-441 from New York (JFK) to London (LHR) on March 16 has been delayed by 4 hours and 30 minutes. New departure: 11:30 PM. Under EU regulation EC 261/2004, you may be entitled to compensation of up to €600.',
  },
  {
    messageId: 'demo-007',
    subject: 'Overdraft fee notice',
    from: 'alerts@firstnationalbank.com',
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    bodyText: 'An overdraft fee of $35.00 has been applied to your checking account ending in 7891 on March 17. Your account balance was -$12.50 when a charge of $45.00 from GroceryMart was processed. Contact us if you believe this fee should be waived.',
  },
  {
    messageId: 'demo-008',
    subject: 'Monthly statement - maintenance fee applied',
    from: 'statements@citybank.com',
    date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    bodyText: 'Your March statement is ready. A monthly maintenance fee of $12.00 has been applied. Your average balance this month was $2,150. Accounts with a balance over $1,500 may qualify for fee waiver. Contact us for details.',
  },
  {
    messageId: 'demo-009',
    subject: 'Subscription renewal: MusicStream Premium Family',
    from: 'billing@musicstream.com',
    date: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    bodyText: 'Your MusicStream Premium Family plan has been renewed at $16.99/month. You have 1 of 6 family member slots in use. You might save money by switching to the Individual plan at $10.99/month.',
  },
  {
    messageId: 'demo-010',
    subject: 'Receipt: DesignTool Pro - Annual Renewal',
    from: 'billing@designtool.co',
    date: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    bodyText: 'You have been charged $199.99 for DesignTool Pro annual renewal. Your account shows last active usage 11 months ago. If you no longer need this tool, you can cancel for a prorated refund within 14 days.',
  },
  {
    messageId: 'demo-011',
    subject: 'Price adjustment opportunity - TV Purchase',
    from: 'customercare@electroworld.com',
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    bodyText: 'The Samsung 65" QLED TV you bought on March 1 for $899.99 is now on sale for $749.99. Our 15-day price match guarantee means you could get $150 back. Visit any store or call us.',
  },
  {
    messageId: 'demo-012',
    subject: 'Flight cancellation notice — Booking #EU2241',
    from: 'support@eurofly.eu',
    date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    bodyText: 'Your flight EF-220 from Paris (CDG) to Barcelona (BCN) on March 12 has been cancelled. We have rebooked you on a flight departing 9 hours later. Under EU261, you may be entitled to €250 compensation for this disruption.',
  },
  {
    messageId: 'demo-013',
    subject: 'Wire transfer fee charged',
    from: 'notifications@globalbank.com',
    date: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    bodyText: 'A wire transfer fee of $25.00 has been charged for your international transfer of $500 to account ending 3344. Your Premium account includes 2 free wire transfers per month, and this was your first transfer. This fee may have been applied in error.',
  },
  {
    messageId: 'demo-014',
    subject: 'Your phone bill summary',
    from: 'billing@mobilenet.com',
    date: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    bodyText: 'Your MobileNet bill for March: $95.00. We notice you have been charged $15.00 for international roaming from a 5-minute call on March 7. Your plan includes 30 minutes of international calls. This charge may be incorrect.',
  },
  {
    messageId: 'demo-015',
    subject: 'Gym membership renewal notice',
    from: 'billing@elitefit.com',
    date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    bodyText: 'Your EliteFit Premium membership has been renewed at $49.99/month. According to our records, you have not checked in for the past 4 months. You may want to review your membership or switch to a basic plan at $19.99/month.',
  },
]
